### ISSUE TITLE
Agregar más validaciones

### ISSUE THREAD

**Issue by jormaechea** [janis-commerce/superstruct#3]
Se necesita agregar (al menos) las siguientes validaciones:

- **integer**: Números enteros
- **positive**: Números positivos
- **positiveOrZero**: Números positivos y zero
- **objectId**: ObjectId de mongodb (12 o 24 caracteres hexa)

**Comment by Nataniel4** [comment]
Tambien estaria bueno agregar la validacion de **UUID**:

- Existe un package para eso: [http://npmjs.com/package/is-uuid](url)

En mis casos uso V4, desconozco si se esta usando uuid diferentes en otros desarrollos.

**Comment by jormaechea** [comment]
@manuelvilche Te diría que para el UUID más que un package, metas una regexp, es bastante fácil de armar..

**Comment by jormaechea** [comment]
Solucionado por #4 
Publicado en la v1.1.0
